### PR TITLE
new docs; integrates with software.acellera.com

### PR DESCRIPTION
**Pull request by alejandrovr**
Hi Stefan,

@j3mdamas and me made some changes on the docs folder to be able to integrate it in software.acellera.com. Also, in the index, what should we include? Because right now align module, for example, is empty, smallmolecule is not visible, while config is.

Let us know!

### CODE REVIEW

**Comment by stefdoerr** [comment]
Hm we should remove the version file. It's automatically generated with the documentation. Anyway I would include basically everything but structured in a nice way. But I can do it myself no problem

**Comment by alejandrovr** [comment]
Hi Stefan! 

Any news over here? I think that we can publish it as it is right now, unless it takes you very little time to change those empty sections. What do you think? 

Bests! ;)

**Comment by stefdoerr** [comment]
If you need it fast we can merge. Otherwise I can try to do it on Friday

**Comment by alejandrovr** [comment]
Let's wait until Friday then! Thanks a lot Stefan!

**Pull request merged**
